DROP DATABASE DB_SPENDING_TOGETHER;

CREATE DATABASE DB_SPENDING_TOGETHER;

USE DB_SPENDING_TOGETHER;

CREATE TABLE TB_USERS(
    USER_ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    NICKNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(511) NOT NULL,
    ACCOUNT_TYPE INT NOT NULL,

    PRIMARY KEY (USER_ID)
);

CREATE TABLE TB_SPREAD_SHEETS(
    SPREAD_SHEET_ID INT NOT NULL AUTO_INCREMENT,
    OWNER_ID INT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    INVITE_CODE VARCHAR(255) NOT NULL,
    CREATION_DATE DATETIME NOT NULL,

    PRIMARY KEY (SPREAD_SHEET_ID),
    FOREIGN KEY (OWNER_ID) REFERENCES TB_USERS (USER_ID) ON DELETE CASCADE
);

CREATE TABLE TB_USERS_SHEETS(
    LINK_ID INT NOT NULL AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    SPREAD_SHEET_ID INT NOT NULL,

    PRIMARY KEY (LINK_ID),
    FOREIGN KEY (USER_ID) REFERENCES TB_USERS (USER_ID),
    FOREIGN KEY (SPREAD_SHEET_ID) REFERENCES TB_SPREAD_SHEETS (SPREAD_SHEET_ID) ON DELETE CASCADE
    
);

CREATE TABLE TB_TAGS(
    TAG_ID INT NOT NULL AUTO_INCREMENT,
    OWNER_ID INT NOT NULL,
    NAME VARCHAR(127) NOT NULL,

    PRIMARY KEY (TAG_ID),
    FOREIGN KEY (OWNER_ID) REFERENCES TB_USERS (USER_ID) ON DELETE CASCADE
);

CREATE TABLE TB_SPENDS(
    SPEND_ID INT NOT NULL AUTO_INCREMENT,
    OWNER_ID INT NOT NULL,
    SPREAD_SHEET_ID INT NOT NULL,
    TAG_ID INT NOT NULL,
    DESCRIPTION VARCHAR(511) NULL,
    VALUE FLOAT NOT NULL,
    DATE DATETIME NOT NULL,


    PRIMARY KEY (SPEND_ID),
    FOREIGN KEY (OWNER_ID) REFERENCES TB_USERS (USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (SPREAD_SHEET_ID) REFERENCES TB_SPREAD_SHEETS(SPREAD_SHEET_ID) ON DELETE CASCADE,
    FOREIGN KEY (TAG_ID) REFERENCES TB_TAGS (TAG_ID)

);

INSERT INTO TB_USERS (NICKNAME, PASSWORD, ACCOUNT_TYPE)
VALUES ('Quenaz', 'Senha12345', 'Premium');

INSERT INTO TB_USERS (NICKNAME, PASSWORD, ACCOUNT_TYPE)
VALUES ('Francelly', 'Senha12345', 'Premium');

INSERT INTO TB_SPREAD_SHEETS (OWNER_ID, NAME)
VALUES (1, 'Financas Casa');

INSERT INTO TB_USERS_SHEETS (USER_ID, SPREAD_SHEET_ID)
VALUES (1, 1);

INSERT INTO TB_USERS_SHEETS (USER_ID, SPREAD_SHEET_ID)
VALUES (2, 1);

INSERT INTO TB_TAGS (TAG_OWNER, NAME)
VALUES (1, 'Casa'), (1, 'Boletos'), (1, 'Comida');

INSERT INTO TB_SPENDS (OWNER_ID, SPREAD_SHEET_ID, TAG_ID, DESCRIPTION, VALUE, DATE)
VALUES (1, 1, 1, 'Compra Mes', 485.89, NOW());

INSERT INTO TB_SPENDS (OWNER_ID, SPREAD_SHEET_ID, TAG_ID, DESCRIPTION, VALUE, DATE)
VALUES (1, 1, 1, 'Conta Luz', 187.12, NOW());

INSERT INTO TB_SPENDS (OWNER_ID, SPREAD_SHEET_ID, TAG_ID, DESCRIPTION, VALUE, DATE)
VALUES (2, 1, 1, 'Conta Agua', 67.21, NOW());

SELECT  TB_SPREAD_SHEETS.SPREAD_SHEET_ID
        ,TB_SPREAD_SHEETS.NAME
        ,TB_SPREAD_SHEETS.INVITE_CODE
        ,TB_SPREAD_SHEETS.CREATION_DATE
        ,TB_USERS.NICKNAME
FROM (TB_SPREAD_SHEETS
    INNER JOIN TB_USERS_SHEETS ON
            TB_SPREAD_SHEETS.SPREAD_SHEET_ID = TB_USERS_SHEETS.SPREAD_SHEET_ID)
    INNER JOIN TB_USERS ON
        TB_SPREAD_SHEETS.OWNER_ID = TB_USERS.USER_ID
WHERE TB_USERS_SHEETS.USER_ID = 2 

